# Generated by Django 5.2.12 on 2026-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
    ]
